// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3GSjspmZgqSrJvlITBNFu-5eOCN8scUE',
    appId: '1:85409185174:web:e8c31050c2937784e431b7',
    messagingSenderId: '85409185174',
    projectId: 'recipe-flutter-lab3',
    authDomain: 'recipe-flutter-lab3.firebaseapp.com',
    storageBucket: 'recipe-flutter-lab3.firebasestorage.app',
    measurementId: 'G-HL5LYBEGJL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAH25bTlJtW_LlUBjqDsSjtCMbIcPf65hA',
    appId: '1:85409185174:android:96743dc45536619be431b7',
    messagingSenderId: '85409185174',
    projectId: 'recipe-flutter-lab3',
    storageBucket: 'recipe-flutter-lab3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7lH2KzE-kTCuji3VYrBSNo-__edFtVDE',
    appId: '1:85409185174:ios:78ad9adbcf047e00e431b7',
    messagingSenderId: '85409185174',
    projectId: 'recipe-flutter-lab3',
    storageBucket: 'recipe-flutter-lab3.firebasestorage.app',
    iosBundleId: 'com.example.misLab2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7lH2KzE-kTCuji3VYrBSNo-__edFtVDE',
    appId: '1:85409185174:ios:78ad9adbcf047e00e431b7',
    messagingSenderId: '85409185174',
    projectId: 'recipe-flutter-lab3',
    storageBucket: 'recipe-flutter-lab3.firebasestorage.app',
    iosBundleId: 'com.example.misLab2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3GSjspmZgqSrJvlITBNFu-5eOCN8scUE',
    appId: '1:85409185174:web:5c3c1cca54dc0207e431b7',
    messagingSenderId: '85409185174',
    projectId: 'recipe-flutter-lab3',
    authDomain: 'recipe-flutter-lab3.firebaseapp.com',
    storageBucket: 'recipe-flutter-lab3.firebasestorage.app',
    measurementId: 'G-1DX02SV3YC',
  );
}
